# Generated by Django 3.2.5 on 2021-07-29 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Author', models.CharField(max_length=15)),
                ('Title', models.CharField(max_length=50)),
                ('ThumbNail', models.ImageField(upload_to='')),
                ('BlogField', models.TextField(max_length=10000)),
                ('isPrivate', models.BooleanField()),
                ('Data', models.DateField(auto_now=True)),
            ],
        ),
    ]
