# Generated by Django 3.2.5 on 2021-07-29 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='ThumbNail',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
