# Generated by Django 3.2.5 on 2021-07-29 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_articles', '0002_alter_blog_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='ThumbNail',
            field=models.ImageField(blank=True, default='default.jpeg', upload_to=''),
        ),
    ]
